[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ecom-notifications"
version = "0.1.0"
description = "E-commerce notifications service (Python-only scaffold)"
requires-python = ">=3.11"
dependencies = ["fastapi>=0.115.0","uvicorn>=0.30.0"]
[tool.setuptools.packages.find]
where = [""]
include = ["app*"]
